---
kind: pipeline
type: docker
name: Linux_PWSH7_Build

platform:
  os: linux
  arch: amd64

steps:
  - name: Environments
    image: mcr.microsoft.com/powershell:latest
    commands:
      - pwsh -NonInteractive -c "& {Import-Module './tools/DroneIO.psm1' -Verbose; Invoke-ShowEnv -Verbose}"
      - pwsh -NonInteractive -c "& {Import-Module './tools/DroneIO.psm1' -Verbose; Invoke-InstallDependencies -Verbose}"
  - name: LintTests
    image: mcr.microsoft.com/powershell:latest
    commands:
      - pwsh -NonInteractive -c "& {Import-Module './tools/DroneIO.psm1'; Invoke-InstallDependencies}"
      - pwsh -NonInteractive -c "& {Import-Module './tools/DroneIO.psm1'; Invoke-Linter}"
  - name: UnitTests
    image: mcr.microsoft.com/powershell:latest
    commands:
      - pwsh -NonInteractive -c "& {Import-Module './tools/DroneIO.psm1'; Invoke-InstallDependencies}"
      - pwsh -NonInteractive -c "& {Import-Module './tools/DroneIO.psm1'; Invoke-UnitTests}"
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: CodeCovToken
      files:
        - coverage.xml

---
kind: pipeline
type: docker

plattform:
  os: windows
  arch: amd64

steps:
   - name: Environments
    image: mcr.microsoft.com/powershell:lts-7.2-nanoserver-1809
    commands:
      - pwsh -NonInteractive -c "& {Import-Module './tools/DroneIO.psm1' -Verbose; Invoke-ShowEnv -Verbose}"
      - pwsh -NonInteractive -c "& {Import-Module './tools/DroneIO.psm1' -Verbose; Invoke-InstallDependencies -Verbose}"
  - name: LintTests
    image: mcr.microsoft.com/powershell:lts-7.2-nanoserver-1809
    commands:
      - pwsh -NonInteractive -c "& {Import-Module './tools/DroneIO.psm1'; Invoke-InstallDependencies}"
      - pwsh -NonInteractive -c "& {Import-Module './tools/DroneIO.psm1'; Invoke-Linter}"
  - name: UnitTests
    image: mcr.microsoft.com/powershell:lts-7.2-nanoserver-1809
    commands:
      - pwsh -NonInteractive -c "& {Import-Module './tools/DroneIO.psm1'; Invoke-InstallDependencies}"
      - pwsh -NonInteractive -c "& {Import-Module './tools/DroneIO.psm1'; Invoke-UnitTests}"
