---
kind: pipeline
type: docker
name: Linux_PWSH7_Build

platform:
  os: linux
  arch: amd64

steps:
  - name: Environments
    image: mcr.microsoft.com/powershell:latest
    commands:
      - |
        pwsh -NonInteractive -c "& {
          Import-Module './tools/DroneIO.psm1' -Verbose;
          Invoke-ShowEnv -Verbose
        }"

  - name: LintTests
    image: mcr.microsoft.com/powershell:latest
    commands:
      - |
        pwsh -NonInteractive -c "& {
          $ErrorActionPreference = 'Stop';
          Import-Module './tools/DroneIO.psm1';
          Invoke-InstallDependencies;
          Invoke-Linter
        }"

  - name: UnitTests
    image: mcr.microsoft.com/powershell:latest
    commands:
      - |
        pwsh -NonInteractive -c "& {
          $ErrorActionPreference = 'Stop';
          Import-Module './tools/DroneIO.psm1';
          Invoke-InstallDependencies;
          Invoke-UnitTest -Verbosity 'Detailed'
        }"

  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: CodeCovToken
      files:
        - coverage.xml
